# Generated by Django 3.0.3 on 2020-05-10 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200510_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='teslim_tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 20, 16, 20, 213305)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='teslim_tarih',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 20, 16, 20, 214304)),
        ),
    ]
